# -*- coding: utf-8 -*-
{
    'name': 'Runnin Number for Stock Pack Operation',
    'author': 'Vizucom Oy',
    'website': '',
    # Categories can be used to filter modules in module listing
    'category': 'stock',
    'version': '0.1',
    # Any module necessary for this one to work correctly
    'depends': ['stock'],
    'data': [
        # security/ir.model.access.csv,
        'views/pack_operation.xml',
        # data/
    ],
    'description':
"""
Running Number for Stock Pack Operations
========================================
* Adds an autogenerated running number for pack operation line.
""",
}
